UserParameter=opnsense.gateway.loss[*],/usr/local/bin/opnsense-zabbix.sh gateway_metric "$1" loss
UserParameter=opnsense.gateway.delay[*],/usr/local/bin/opnsense-zabbix.sh gateway_metric "$1" delay
UserParameter=opnsense.gateway.status[*],/usr/local/bin/opnsense-zabbix.sh gateway_metric "$1" status_translated
UserParameter=opnsense.if.inerrors[*],netstat -n -I "$1" -bdi | awk 'NR==2 {print $5+0}'
UserParameter=opnsense.if.outerrors[*],netstat -n -I "$1" -bdi | awk 'NR==2 {print $10+0}'
